Лабораторная работа №2
Programming-Classrooms/practicalworks-IvanSolovyov23 pull request #11
Opened 2024-03-31 20:34 UTC by IvanSolovyov23

Лабораторной работы №2
Реализовать класс String (обязательно конструкторы, деструктор, геттеры, сеттеры и операторы + = += << >>)

2024-05-06 06:53 UTC, AnnaSatolina requested changes
Слетела кодировка комментов

2024-05-06 06:53 UTC, AnnaSatolina commented on laboratory-task-12/src/class/String.cpp
> +/* =========================================================================== */
Перенос с винды не прошёл бесследно

2024-05-06 06:53 UTC, AnnaSatolina commented on laboratory-task-12/src/class/String.cpp
> +}
Метод клон

2024-05-06 06:53 UTC, AnnaSatolina commented on laboratory-task-12/src/class/String.cpp
> +}
Логическая ошибка, задаёшь this->size = 0, почему?

2024-05-06 06:53 UTC, AnnaSatolina commented on laboratory-task-12/src/class/String.cpp
> +}
nullptr

2024-05-06 06:53 UTC, AnnaSatolina commented on laboratory-task-12/src/class/String.cpp
> +}
Лучше передавать буфер как аргумент в эту функцию, для заполнения данными

2024-05-06 06:53 UTC, AnnaSatolina commented on laboratory-task-12/src/class/String.cpp
> +}
Если поле назвал size, то и геттер нужно назвать также

2024-05-23 07:59 UTC, AlexandrOsiptsov requested changes
В целом чётко, есть небольшие недочёты по переписыванию уже существующей логики. Обрати внимание на комменты Анны Викторовны

2024-05-23 07:59 UTC, AlexandrOsiptsov commented on laboratory-task-12/src/class/BUILD
> +)
Если назвал модуль String, то и папку называй также

2024-05-23 07:59 UTC, AlexandrOsiptsov commented on laboratory-task-12/src/class/String.cpp
> +}
Поддерживаю

2024-05-23 07:59 UTC, AlexandrOsiptsov commented on laboratory-task-12/src/class/String.cpp
> +}
Выделенную память в итоге потерял

2024-05-23 07:59 UTC, AlexandrOsiptsov commented on laboratory-task-12/src/class/String.cpp
> +}
Вот этот метод можно и в деструкторе заюзать

2024-05-25 15:47 UTC, AlexandrOsiptsov requested changes
Помеченные замечания не исправил, перечитай

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, merged